### PR TITLE
Update Dockerfile to expose port again

### PR DESCRIPTION
**Pull request by wallyqs**
We missed adding this to the new dockerfile: https://github.com/nats-io/nats-surveyor/blob/main/Dockerfile#LL18

### CODE REVIEW

**Comment by samuelattwood** [comment]
@wallyqs Strictly speaking `EXPOSE` is just an informational instruction, it doesn't really have any impact on function. I'm not opposed to adding it, but I did try to format that Dockerfile to be for a generic go app and would usually add application-specifics in an additional image layer

**Comment by caleblloyd** [comment]
Agree with @samuelattwood Expose is simply metadata. Someone could override args to listen on a different port.

Is there a particular issue this links to?

**Comment by caleblloyd** [comment]
@wallyqs can we close this?

**Comment by wallyqs** [comment]
what are the cons of adding it?

**Comment by wallyqs** [comment]
user worked around the issue so it can be closed for now, could reopen if issue comes again

**Pull request closed without merging**
